export interface WPCV {
  id: number;
  slug: string;
  status: 'publish' | 'draft' | 'private';
  type: 'cv';
  link: string;
  title: { rendered: string };
  content: { rendered: string; protected: boolean };
  acf: ACFFields;
  _links: Record<string, unknown>;
}

export interface ACFFields {
  firma?: string;
  stellenbezeichnung?: string;
  ansprechpartner?: string;
  anstellungsart_gewunscht?: string;
  profilbild?: WPImage;
  vorname?: string;
  nachname?: string;
  adresse?: string;
  plz?: number | string;
  ort?: string;
  e_mail?: string;
  telefon?: string;
  bereich?: string;
  beworbene_anstellungsart?: string;
  copyright_text?: string;
  facebook_link?: string;
  linkedin_link?: string;
  xing_link?: string;
  das_zeichnet_mich_aus?: string;
  das_mag_ich_nicht?: string;
  uber_mich_text?: string;
  bereich_1?: string;
  bereich_1_text?: string;
  bereich_1_icon?: WPImage;
  bereich_2?: string;
  bereich_2_text?: string;
  bereich_2_icon?: WPImage;
  bereich_3?: string;
  bereich_3_text?: string;
  bereich_3_icon?: WPImage;
  bereich_4?: string;
  bereich_4_text?: string;
  bereich_4_icon?: WPImage;
  cta_header?: string;
  cta_text?: string;
  sprachen_anzeigen?: string;
  sprache_1?: string;
  sprache_2?: string;
  sprache_3?: string;
  sprache_1_starke?: number | string;
  sprache_2_starke?: number | string;
  sprache_3_starke?: number | string;
  sprache_1_farbe?: string;
  sprache_2_farbe?: string;
  sprache_3_farbe?: string;
  skills_text?: string;
  hard_skill_1?: string;
  hard_skill_2?: string;
  hard_skill_3?: string;
  hard_skill_4?: string;
  hard_skill_5?: string;
  hard_skill_6?: string;
  hard_skill_7?: string;
  hard_skill_8?: string;
  hard_skill_9?: string;
  hard_skill_10?: string;
  hard_skill_11?: string;
  hard_skill_12?: string;
  hard_skill_1_starke?: number | string;
  hard_skill_2_starke?: number | string;
  hard_skill_3_starke?: number | string;
  hard_skill_4_starke?: number | string;
  hard_skill_5_starke?: number | string;
  hard_skill_6_starke?: number | string;
  hard_skill_7_starke?: number | string;
  hard_skill_8_starke?: number | string;
  hard_skill_9_starke?: number | string;
  hard_skill_10_starke?: number | string;
  hard_skill_11_starke?: number | string;
  hard_skill_12_starke?: number | string;
  hard_skill_1_farbe?: string;
  hard_skill_2_farbe?: string;
  hard_skill_3_farbe?: string;
  hard_skill_4_farbe?: string;
  hard_skill_5_farbe?: string;
  hard_skill_6_farbe?: string;
  hard_skill_7_farbe?: string;
  hard_skill_8_farbe?: string;
  hard_skill_9_farbe?: string;
  hard_skill_10_farbe?: string;
  hard_skill_11_farbe?: string;
  hard_skill_12_farbe?: string;
  soft_skill_1?: string;
  soft_skill_2?: string;
  soft_skill_3?: string;
  soft_skill_4?: string;
  soft_skill_5?: string;
  soft_skill_6?: string;
  berufserfahrung_text?: string;
  berufserfahrung_1_zeitraum?: string;
  berufserfahrung_1_titel?: string;
  berufserfahrung_1_beschreibung?: string;
  berufserfahrung_2_zeitraum?: string;
  berufserfahrung_2_titel?: string;
  berufserfahrung_2_beschreibung?: string;
  berufserfahrung_3_zeitraum?: string;
  berufserfahrung_3_titel?: string;
  berufserfahrung_3_beschreibung?: string;
  berufserfahrung_4_zeitraum?: string;
  berufserfahrung_4_titel?: string;
  berufserfahrung_4_beschreibung?: string;
  berufserfahrung_5_zeitraum?: string;
  berufserfahrung_5_titel?: string;
  berufserfahrung_5_beschreibung?: string;
  weiterbildung_text?: string;
  weiterbildung_1_titel?: string;  weiterbildung_1_inhalt?: string;
  weiterbildung_2_titel?: string;  weiterbildung_2_inhalt?: string;
  weiterbildung_3_titel?: string;  weiterbildung_3_inhalt?: string;
  weiterbildung_4_titel?: string;  weiterbildung_4_inhalt?: string;
  weiterbildung_5_titel?: string;  weiterbildung_5_inhalt?: string;
  weiterbildung_6_titel?: string;  weiterbildung_6_inhalt?: string;
  weiterbildung_7_titel?: string;  weiterbildung_7_inhalt?: string;
  weiterbildung_8_titel?: string;  weiterbildung_8_inhalt?: string;
  weiterbildung_9_titel?: string;  weiterbildung_9_inhalt?: string;
  weiterbildung_10_titel?: string; weiterbildung_10_inhalt?: string;
  weiterbildung_11_titel?: string; weiterbildung_11_inhalt?: string;
  weiterbildung_12_titel?: string; weiterbildung_12_inhalt?: string;
  ausbildung_text?: string;
  ausbildung_1_titel?: string;  ausbildung_1_inhalt?: string;
  ausbildung_2_titel?: string;  ausbildung_2_inhalt?: string;
  ausbildung_3_titel?: string;  ausbildung_3_inhalt?: string;
  portfolio_text?: string;
  portfolio_1_titel?: string;  portfolio_1_text?: string;  portfolio_1_bild?: WPImage;  portfolio_1_link?: string;
  portfolio_2_titel?: string;  portfolio_2_text?: string;  portfolio_2_bild?: WPImage;  portfolio_2_link?: string;
  portfolio_3_titel?: string;  portfolio_3_text?: string;  portfolio_3_bild?: WPImage;  portfolio_3_link?: string;
  portfolio_4_titel?: string;  portfolio_4_text?: string;  portfolio_4_bild?: WPImage;  portfolio_4_link?: string;
  portfolio_5_titel?: string;  portfolio_5_text?: string;  portfolio_5_bild?: WPImage;  portfolio_5_link?: string;
  portfolio_6_titel?: string;  portfolio_6_text?: string;  portfolio_6_bild?: WPImage;  portfolio_6_link?: string;
  kontakt_text?: string;
}

export interface WPImage {
  ID: number;
  id: number;
  title: string;
  filename: string;
  url: string;
  alt: string;
  mime_type: string;
  width: number;
  height: number;
  sizes: {
    thumbnail: string;
    medium: string;
    large: string;
    [key: string]: string | number;
  };
}

export interface CVPage extends WPCV {
  acf: ACFFields;
}
